#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: IvanLu
 * Date: 2019/4/7
 * Time: 2:03
 */

use BunnyPHP\BunnyPHP;

const APP_PATH = __DIR__ . '/';
const APP_DEBUG = true;
date_default_timezone_set('PRC');
require(APP_PATH . 'vendor/autoload.php');
(new BunnyPHP(BunnyPHP::MODE_CLI))->run();